export const ITEMS_CREATE_PENDING = 'ITEMS_CREATE_PENDING'
export const ITEMS_CREATE_SUCCESS = 'ITEMS_CREATE_SUCCESS'
export const ITEMS_CREATE_FAILURE = 'ITEMS_CREATE_FAILURE'

export const ITEMS_GET_PENDING = 'ITEMS_GET_PENDING'
export const ITEMS_GET_SUCCESS = 'ITEMS_GET_SUCCESS'
export const ITEMS_GET_FAILURE = 'ITEMS_GET_FAILURE'

export const ITEMS_UPDATE_PENDING = 'ITEMS_UPDATE_PENDING'
export const ITEMS_UPDATE_SUCCESS = 'ITEMS_UPDATE_SUCCESS'
export const ITEMS_UPDATE_FAILURE = 'ITEMS_UPDATE_FAILURE'

export const ITEMS_DELETE_PENDING = 'ITEMS_DELETE_PENDING'
export const ITEMS_DELETE_SUCCESS = 'ITEMS_DELETE_SUCCESS'
export const ITEMS_DELETE_FAILURE = 'ITEMS_DELETE_FAILURE'
